version: "3"
services:
  kinesis:
    image: instructure/kinesalite:latest
    ports:
      - "4567:4567"

  dynamodb:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"

  sqs:
    image: softwaremill/elasticmq-native:latest
    ports:
      - "9324:9324"

  s3:
    image: minio/minio:latest
    command: server /data
    ports:
      - "9000:9000"
