version: "3"
services:
  kinesis:
    image: dlsniper/kinesalite:latest
    ports:
      - "4567:4567"

  dynamodb:
    image: cnadiminti/dynamodb-local:latest
    ports:
      - "8000:8000"

  sqs:
    image: softwaremill/elasticmq:latest
    ports:
      - "9324:9324"

  s3:
    image: minio/minio:RELEASE.2020-06-14T18-32-17Z
    command: server /data
    ports:
      - "9000:9000"
