version: "3"
services:

  dynamodb:
    image: cnadiminti/dynamodb-local:latest
    ports:
      - "8000:8000"
  dynamodb-create:
    image: infrastructureascode/aws-cli:latest
    links:
      - dynamodb
    entrypoint: sh
    command: ./create-tables.sh
    volumes:
      - ./scripts/create-tables.sh:/project/create-tables.sh:ro
    environment:
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - AWS_DEFAULT_REGION=eu-west-1
      - AWS_ENDPOINT_URL=http://dynamodb:8000

  sqs:
    image: softwaremill/elasticmq:latest
    ports:
      - "9324:9324"
  sqs-create:
    image: infrastructureascode/aws-cli:latest
    links:
      - sqs
    entrypoint: sh
    command: ./create-queues.sh
    volumes:
      - ./scripts/create-queues.sh:/project/create-queues.sh:ro
    environment:
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - AWS_DEFAULT_REGION=eu-west-1
      - AWS_ENDPOINT_URL=http://sqs:9324

  kinesis:
    image: dlsniper/kinesalite:latest
    ports:
      - "4567:4567"
  kinesis-create:
    image: infrastructureascode/aws-cli:latest
    links:
      - kinesis
    entrypoint: sh
    command: ./create-streams.sh
    volumes:
      - ./scripts/create-streams.sh:/project/create-streams.sh:ro
    environment:
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - AWS_DEFAULT_REGION=eu-west-1
      - AWS_ENDPOINT_URL=http://kinesis:4567
  s3:
    image: minio/minio:RELEASE.2020-06-14T18-32-17Z
    command: server /data
    ports:
      - "9000:9000"
    environment:
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=locallocal
      - MINIO_ACCESS_KEY=local
      - MINIO_SECRET_KEY=locallocal
      - AWS_DEFAULT_REGION=eu-west-1
      - AWS_ENDPOINT_URL=http://s3:9000

  s3-create:
    image: infrastructureascode/aws-cli:latest
    links:
      - s3
    entrypoint: sh
    command: ./create-buckets.sh
    volumes:
      - ./scripts/create-buckets.sh:/project/create-buckets.sh:ro
    environment:
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=locallocal
      - AWS_DEFAULT_REGION=eu-west-1
      - AWS_ENDPOINT_URL=http://s3:9000
